const mockReviews = [
  {
    restaurant: 101,
    userName: 'Beth Johnson',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/BJ.png',
    userLocation: 'Cleveland, Ohio',
    rating: 5,
    date: '2017-12-17T11:24:00.000Z',
    reviewBody: 'HOLY MOLY! The fettucine alfredo! The pesto ravioli! Everything looked and tasted amazing! And their service ... WOW! Timothy was the absolute best!  Honestly, I wish I could give this place ten stars -- they deserve it!',
    useful: 4,
    funny: 6,
    cool: 5,
  },
  {
    restaurant: 101,
    userName: 'Makan Azarshahy',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MA.jpg',
    userLocation: 'Portland, OR',
    rating: 5,
    date: '2017-12-19T11:24:00.000Z',
    reviewBody: 'This place is an absolute gem! I love coming here because the atmosphere of the place is relaxing and the coffee is great! The staff are INCREDIBELY kind. Always a wonderful experience!',
    useful: 0,
    funny: 1,
    cool: 6,
  },
  {
    restaurant: 101,
    userName: 'Mat Bagnall',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MB.jpg',
    userLocation: 'Auckland, New Zealand',
    rating: 5,
    date: '2017-12-05T11:24:00.000Z',
    reviewBody: 'I consider myself a foodie and like to think I would have made an excellent restaurant critic if I\'d never gone to Hack Reactor. That said, I can think of nothing negative to say about this place. Everything exceeded my very high expectations. 5 stars.',
    useful: 1,
    funny: 5,
    cool: 5,
  },
  {
    restaurant: 102,
    userName: 'Wayman Ng',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/WN.jpg',
    userLocation: 'Salt Lake City, UT',
    rating: 5,
    date: '2018-01-05T14:40:00.000Z',
    reviewBody: 'My mom and I both loved this place! I took her there to celebrate her birthday and Tina really went above and beyond to make my mom feel special.',
    useful: 6,
    funny: 4,
    cool: 5,
  },
  {
    restaurant: 102,
    userName: 'Airyque Ervin',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/AE.jpg',
    userLocation: 'Miami, FL',
    rating: 5,
    date: '2018-01-09T02:23:00.000Z',
    reviewBody: 'I can\'t believe I\'d never heard of this place until this past week. Either way, I know about it now and it can become my new favorite place for French cuisine.',
    useful: 1,
    funny: 3,
    cool: 4,
  },
  {
    restaurant: 102,
    userName: 'Makan Azarshahy',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MA.jpg',
    userLocation: 'Portland, OR',
    rating: 5,
    date: '2018-01-13T22:23:00.000Z',
    reviewBody: 'This place is an absolute gem! I love coming here because the atmosphere of the place is relaxing and the coffee is great! The staff are INCREDIBELY kind. Always a wonderful experience!',
    useful: 1,
    funny: 2,
    cool: 1,
  },
  {
    restaurant: 103,
    userName: 'Namson Leung',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/NL.jpg',
    userLocation: 'Seattle, WA',
    rating: 3,
    date: '2018-01-13T22:23:00.000Z',
    reviewBody: 'Overall, good food, but I am a stickler for service and it greatly lacked this time around. Aside from the first staff member we encountered, our waiter did not check up on us until we had already paid the bill in which another staff member helped us with. I guess it was just too busy. On another note, nice location and atmosphere, but again, service lacks and parking can be difficult.',
    useful: 2,
    funny: 5,
    cool: 5,
  },
  {
    restaurant: 103,
    userName: 'Nicholas Peyrichou',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/NP.jpg',
    userLocation: 'New Orleans, LA',
    rating: 2,
    date: '2018-01-11T03:23:00.000Z',
    reviewBody: 'Overall take: I thought this place was just okay. Granted, going out to eat in general is expensive, but I felt like the prices were a bit high for the quality of food delivered.',
    useful: 6,
    funny: 3,
    cool: 2,
  },
  {
    restaurant: 103,
    userName: 'Angel Hernandez',
    userPhoto: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/AH.jpg',
    userLocation: 'San Francisco, CA',
    rating: 4,
    date: '2018-02-01T05:47:00.000Z',
    reviewBody: 'The food was good.  I would recommend the buttermilk pancake stack and the jam selection.  Why not 5 stars? Because they don\'t have a cocktails, only wine and beer.  I would have loved an old fashioned or whiskey sour with my meal.',
    useful: 0,
    funny: 4,
    cool: 0,
  },
];

module.exports = mockReviews;
